### ISSUE TITLE
Add List import support.

### ISSUE THREAD

**Issue by KathanP19** [Lactea98/smuggler.py#1]
it will great to be able to take list of subdomains as input

**Comment by Universe1122** [comment]
Thanks for comments.
It updated v 0.2 including your reported issue.

Thanks for using my tools!!

**Comment by KathanP19** [comment]
What is the option for importing list?

**Comment by Universe1122** [comment]
Oh.. I forgot added option...
It updated new option for importing list.

You can use this option "--file [yourlist.txt]" like this.

Example, you save seperate url list using new line.

https[:]//test.com
https[:]//aaaa.com
https[:]//bbbb.com

And then, Enter command line.

`
python3 smuggler.py --file list.txt
`
Then, you can see result.


Always welcome any new bugs or questions.

**Comment by KathanP19** [comment]
Thank you, for adding the feature ,there is also another tool smuggler.py by defparam , but it has lots of false positive , your tool is better in that case.
Will let you know if any issues in future or any feature to add.😄
